// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiguelGondresPA2.DAL;

namespace MiguelGondresPA2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("MiguelGondresPA2.Entidades.LlamadaDetalle", b =>
                {
                    b.Property<int>("LlamadaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LlamadaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("LlamadaDetalleId");

                    b.HasIndex("LlamadaId");

                    b.ToTable("LlamadaDetalle");

                    b.HasData(
                        new
                        {
                            LlamadaDetalleId = 1,
                            LlamadaId = 1,
                            Problema = "Sin Cuerdas",
                            Solucion = "Comprar Cuerdas"
                        },
                        new
                        {
                            LlamadaDetalleId = 2,
                            LlamadaId = 2,
                            Problema = "Sin Bateria",
                            Solucion = "Comprar Bateria"
                        });
                });

            modelBuilder.Entity("MiguelGondresPA2.Entidades.Llamadas", b =>
                {
                    b.Property<int>("LlamadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("LlamadaId");

                    b.ToTable("Llamadas");

                    b.HasData(
                        new
                        {
                            LlamadaId = 1,
                            Descripcion = "Guitarra"
                        },
                        new
                        {
                            LlamadaId = 2,
                            Descripcion = "Celular"
                        });
                });

            modelBuilder.Entity("MiguelGondresPA2.Entidades.LlamadaDetalle", b =>
                {
                    b.HasOne("MiguelGondresPA2.Entidades.Llamadas", null)
                        .WithMany("LlamadaDetalle")
                        .HasForeignKey("LlamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
